config/routes.rb
Rails.application.routes.draw do
  get 'bids/place'

  get 'bids/completed'

  get 'development/coming_soon'

  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def place
  end

  def completed
  end
end

app/controllers/development_controller.rb
class DevelopmentController < ApplicationController
  def coming_soon
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/development_helper.rb
module DevelopmentHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bids/completed.html.haml
.page-header
  %h2 Thanks For Your Order
.jumbotron
  %h4.content
    :markdown
      Your order is currently being pushed to handlers throughout California.
      
      You should be hearing back in the next 2 to 3 business days if someone is
      willing to accept your order.

app/views/bids/place.html.haml
.page-header
  %h2 Place an Order for Califonia Almonds

.panel.panel-default
  .panel-body
    :markdown
      **Cut out the Middlemen**

      By placing an order here, your offer will automatically be pushed
      **directly** to California handlers.


%form{ action:bids_completed_path, method:'GET' }
  .form-group.row
    %label.col-xs-2.form-control-label Email
    .col-xs-10
      %input.form-control

  .form-group.row
    %label.col-xs-2.form-control-label Type 
    .col-xs-10
      %select.form-control
        %option{disabled:true, selected:true} -- Select --
        %option Nonpareil
        %option Califonia
        %option Mission
        %option{disabled:true} (More Varieties To Come)

  .form-group.row
    %label.col-xs-2.form-control-label LBs 
    .col-xs-10
      %input.form-control
      %span.text-muted.pull-right
        Current Estimated Price/LB: $3.93


  .form-group.row
    %label.col-xs-2.form-control-label Quality 
    .col-xs-10
      %input.form-control

  .form-group.row
    %label.col-xs-2.form-control-label Asking Price 
    .col-xs-10
      %input.form-control

  .form-group.row
    %label.col-xs-2.form-control-label Notes to Seller 
    .col-xs-10
      %textarea.form-control

  %button.btn.btn-primary.pull-right Submit
  
  

app/views/development/coming_soon.html.haml
.page-header
  %h2 Coming Soon
.jumbotron
  %h4.content
    :markdown
      Much of our application is still in development, but we are working
      hard to get all future features into production.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AlmondTech
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    // Nav Bar
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{ href:root_path, title:"AlmondTech" }
            %strong AlmondTech
        %div
          %ul.nav.navbar-nav
            %li.active= link_to 'Home', root_path
        %div
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to development_coming_soon_path do
                %span.glyphicon.glyphicon-user
                Sign Up
            %li
              = link_to development_coming_soon_path do
                %span.glyphicon.glyphicon-log-in
                Log In
    .container
      = yield

app/views/welcome/index.html.haml
.page-header
  %h2 We Revolutionize The Way Almonds Are Traded
.row
  .col-xs-3= image_tag 'almond.png', class:'img-responsive'
  .col-xs-9
    .jumbotron
      %h4.content
        :markdown
          **Streamline Your Almond Transactions**
          
          <sub>AlmondTech is the easiest place to buy almonds on the global wholesale market. We eliminate all the "middlemen" so the buyers get the lowest price possible. When you place an order through AlmondTech, your order will immediately be pushed to handlers and sellers all over California, giving your order the maximum amount of exposure. Sellers will be able to compete for your business with lower counter offers, ensuring that you won’t be over paying current market standard. With AlmondTech, you will never again wonder whether you are getting the current, lowest price possible.</sub>

          *Remove the hassle*

          *Know you're getting the best prices*
          
    %button.btn.btn-default.btn-block.center-block= link_to 'Place an Order to All of California', bids_place_path